---
title: "About"
---

# About me

I am Alicia Ho, an NUS student majoring in Music at the YST Conservatory of Music.

# Why did I choose this topic?
My initial idea was to analyse mental health conditions based on the type of music that one listens to. Since I study music, I thought that this topic would be more relatable to me. However, I found that the trends were not clear and there was no strong conclusion that could be drawn from the data. Hence, I decided to explore mental health disorders on a more general level.

I think that in Singapore, and maybe some other parts of the world, mental health is still not talked about enough. There is still some stigma attached to getting therapy and older generations may think that getting help for certain mental conditions is just a sign of weakness. However, I think that these mental health disorders should be dealt with more seriously as it affects the quality of our lives to a large extent. 

Hence, I hope that this visualisation will bring to light the prevalence of mental health disorders and certain trends that are observed based on this data. 

# Credits

The link to the data of mental health disorders worldwide can be found here: https://www.kaggle.com/datasets/thedevastator/uncover-global-trends-in-mental-health-disorder?resource=download

The link to the leaflet data to create the world map can be found here:
https://github.com/lvictory/maps-data/blame/master/world.geo.json 

# References
Asciutto, R., Lugo, A., Pacifici, R., Colombo, P., Rota, M., Carlo La Vecchia, & Gallus, S. (2015). The Particular Story of Italians’ Relation with Alcohol: Trends in Individuals’ Consumption by Age and Beverage Type. Alcohol and Alcoholism (Oxford), 51(3), 347–353. https://doi.org/10.1093/alcalc/agv121

Ceccanti, M., Iannitelli, A., & Fiore, M. (2018). Italian Guidelines for the treatment of alcohol dependence. Rivista Di Psichiatria, 53(3), 105–106. https://www.rivistadipsichiatria.it/archivio/2925/articoli/29410/

Hook, K., & Bogdanov, S. (2021). Mental health care in Eastern Europe and Central Asia: An analysis of needs and a call for greater investment. The Lancet Regional Health Europe, 10, 100182–100182. https://doi.org/10.1016/j.lanepe.2021.100182

Pavel Grigoriev, & Bobrova, A. (2020). Alcohol control policies and mortality trends in Belarus. Drug and Alcohol Review, 39(7), 805–817. https://doi.org/10.1111/dar.13032

Queensland Brain Institute. (2023, July 31). Half of World’s Population Will Experience a Mental Health Disorder. Harvard.edu. https://hms.harvard.edu/news/half-worlds-population-will-experience-mental-health-disorder

Shahbazi, F., Shahbazi, M., & Jalal Poorolajal. (2022). Association between socioeconomic inequality and the global prevalence of anxiety and depressive disorders: an ecological study. General Psychiatry, 35(3), e100735–e100735. https://doi.org/10.1136/gpsych-2021-100735

Syed Fahad Javaid, Ibrahim Jawad Hashim, Muhammad Jawad Hashim, Stip, E., Mohammed Abdul Samad, & Alia Al Ahbabi. (2023). Epidemiology of anxiety disorders: global burden and sociodemographic associations. Middle East Current Psychiatry, 30(1). https://doi.org/10.1186/s43045-023-00315-3

World Health Organization. (2022a, June 8). Mental disorders. Who.int; World Health Organization: WHO. https://www.who.int/news-room/fact-sheets/detail/mental-disorders

World Health Organization. (2022b, June 17). Mental health. Who.int; World Health Organization: WHO. https://www.who.int/en/news-room/fact-sheets/detail/mental-health-strengthening-our-response

World Health Organization. (2022c, November 9). Revitalizing mental health reforms in the Western Balkans after COVID-19. Who.int; World Health Organization: WHO. https://www.who.int/europe/news/item/09-11-2022-revitalizing-mental-health-reforms-in-the-western-balkans-after-covid-19 