---
title: "Alicia's Website"
---

# Data Visualisation

The link to the data I used can be found here: https://www.kaggle.com/datasets/thedevastator/uncover-global-trends-in-mental-health-disorder?resource=download

```{=html}
<iframe height="600" width="100%" frameborder="no" src="https://1ua3vn-alicia-ho.shinyapps.io/personal_app/"> </iframe>
```

```{r eval=TRUE, include=FALSE}
library(tidyverse)
data <- read.csv("/Users/aliciaho/Desktop/nus yst/NM2207/NM2207 Project/Mental health Depression disorder Data.csv")
small_data <- data %>% select(-c(index, Code))
```

Plot showing the trend of depression in Singapore from 1990-2017

```{r eval = TRUE, echo=FALSE}
sgp_data <- data %>% select(-c(index, Entity)) %>%
  filter(Code == "SGP", Year >=1990) %>%
  select(Year, Depression....) %>%
  na.omit()
ggplot(sgp_data) +
  aes(x = Year, y = Depression....) + 
  geom_point()+
  labs(x = "Year", y = "Percentage of population experiencing depression", title = "Trend of depression rates in Singapore from 1990-2017") +
  theme_bw() +
  theme(axis.text.x = element_text(colour = "grey20", size = 10, angle = 90, hjust = 0.5, vjust = 0.5)
  )
```

Another graph

```{r eval=TRUE, include=FALSE}
data$Schizophrenia.... <- as.numeric(data$Schizophrenia....)
data$Bipolar.disorder....<- as.numeric(data$Bipolar.disorder....)
data$Eating.disorders.... <- as.numeric(data$Eating.disorders....)
```

```{r eval=TRUE, echo=FALSE}
newsgp_data <- data %>% select(-c(index, Entity)) %>%
  filter(Code == "SGP", Year >=1990, Eating.disorders.... <100) %>%
  pivot_longer(cols = Schizophrenia....:Alcohol.use.disorders...., names_to = "disorder_type", values_to = "percentage") %>%
  select(Year, disorder_type, percentage) %>%
  na.omit()
print(ggplot(newsgp_data) +
  aes(x = Year, y = percentage) +
  geom_point() +
  facet_wrap(~ disorder_type, ncol =2))
```

```{r eval=TRUE, echo=FALSE}
newsgp_data <- data %>% select(-c(index, Entity)) %>%
  filter(Code == "SGP", Year >=1990, Eating.disorders.... <100) %>%
  pivot_longer(cols = Schizophrenia....:Alcohol.use.disorders...., names_to = "disorder_type", values_to = "percentage") %>%
  select(Year, disorder_type, percentage) %>%
  na.omit()
print(ggplot(newsgp_data) +
  aes(x = Year, y = percentage, color=disorder_type) +
  geom_point() +
    theme_bw() +
  theme(axis.text.x = element_text(colour = "grey20", size = 10, angle = 90, hjust = 0.5, vjust = 0.5) 
        ) +
    labs(title = "Overall trend of mental health disorders in Singapore from 1990-2017", x = "Year", y = "Percentage of Singapore population") +
    scale_color_discrete(
      name = "Type of mental health\ndisorder",
      labels = c("Alcohol use disorder", "Anxiety disorder", "Bipolar disorder", "Depression", "Drug use disorder", "Eating disorder", "Schizophrenia")
    )
  )
```
